version: "3.9"
services:
  devcontainer-svelte-template:
    container_name: dev-devcontainer-svelte-template
    build: .
    working_dir: /workspaces
    command: /bin/sh -c "while sleep 1000; do :; done"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/workspaces:cached
      - dev-devcontainer-svelte-template:/workspaces

volumes:
  dev-devcontainer-svelte-template: