version: "3.9"
name: devcontainer-svelte-template

services:
  devcontainer-svelte-template:
    container_name: dev-devcontainer-svelte-template
    environment:
      - NODE_ENV=development
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    ports:
      - 5174:5174
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - dev-devcontainer-svelte-template:/workspaces
      - ~/.gitconfig:/root/.gitconfig

networks:
  devcontainer-svelte-template-network:
    name: devcontainer-svelte-template-network
    driver: bridge

volumes:
  dev-devcontainer-svelte-template:
