# version: "3.9"
# name: devcontainer-svelte-template

# services:
#   devcontainer-svelte-template:
#     container_name: dev-devcontainer-svelte-template
#     environment:
#       - NODE_ENV=development
#     build: .
#     ports:
#       - 5174:5174
#     command: /bin/sh -c "while sleep 1000; do :; done"
#     volumes:
#       - dev-devcontainer-svelte-template:/workspaces
#       - ~/.gitconfig:/root/.gitconfig

# volumes:
#   dev-devcontainer-svelte-template:


version: "3.9"
services:
  devcontainer-svelte-template:
    container_name: dev-devcontainer-svelte-template
    build: .
    working_dir: /workspaces
    volumes:
      - .:/workspaces:cached
      - dev-devcontainer-svelte-template:/workspaces
    command: /bin/sh -c "while sleep 1000; do :; done"

volumes:
  dev-devcontainer-svelte-template: